---
- name: Gather facts and display it
  hosts: dockerhost
  tasks:
    - name: Display all gathered facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Display the currently running kernel version and distro
      ansible.builtin.debug:
        msg: "The kernel version is {{ ansible_facts.kernel }} and the distro is {{ ansible_facts.distribution }}"
